[workspace]
resolver = "2"

members = [
    "ckb_deterministic",
    "tests",
    "example_libs/deterministic_cdp",
    "example_contracts/deterministic_cdp_project_type",
]


[profile.release]
overflow-checks = true
strip = true
codegen-units = 1
