[package]
name = "deterministic_cdp_project"
version = "0.1.0"
edition = "2021"

[features]
default = []
library = []

[[bin]]
name = "deterministic_cdp_project"
path = "src/main.rs"

[dependencies]
ckb-std = { version = "0.16.4", default-features = false, features = ["allocator", "ckb-types", "dummy-atomic"] }
deterministic-cdp-shared = { path = "../../example_libs/deterministic_cdp_shared" }
ckb_deterministic = { path = "../../ckb_deterministic", default-features = false }

