[package]
name = "deterministic_cdp"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
ckb_deterministic = { path = "../../ckb_deterministic" }
deterministic_common = { path = "../deterministic_common" }